#!/bin/sh

. /etc/profile

count=`ps -ef | grep $1 | grep -v grep |grep -v '/bin/sh' | awk '{print $2}'| wc -l`

if [ $count -gt 0 ];then
    echo ''
else
    echo "$1服务器进程不存在，`date '+%Y-%m-%d %H:%M:%S'`重新启动" >> /opt/restart_tomcat.log
    sh /opt/tomcat/$1/bin/startup.sh
fi


echo '' > /usr/local/crontab/restart_tomcat/all_check.sh

cat > /usr/local/crontab/restart_tomcat/all_check.sh<< EOF
#!/bin/sh
. /etc/profile
/usr/local/crontab/restart_tomcat/check_tomcat.sh tomcat-1
/usr/local/crontab/restart_tomcat/check_tomcat.sh tomcat-2
/usr/local/crontab/restart_tomcat/check_tomcat.sh tomcat-3
EOF


